### PR TITLE
Vcd2wavedrom pr autoconfig

### PR DESCRIPTION
**Pull request by Fresher14**
Here is a proposal for new feature: full automatic mode

- config file becomes optional
- all timings are normalized
- in case of asynchronism, upsampling up to 4 is applied
- bug correction for bus data when initial content is 0 or 1 (considered as a simple signal previously)
- tested with Cadence tools

auto mode is activated when no config file is specified

### CODE REVIEW

**Comment by Fresher14** [comment]
@andresmanelli 
Did you have time to try it ?

**Comment by andresmanelli** [comment]
I tested briefly the PR and it looks nice ! Before I can merge this, I need to finish some rework that I have in progress, so it might take some time for me to review this. I'll keep in touch !

**Comment by Fresher14** [comment]
Any update ? Can I delete my branch on my side without side effect here ? I'm new to publishing on GitHub.

**Comment by Fresher14** [comment]
Hello. Any update ?

**Comment by nobodywasishere** [comment]
> Any update ? Can I delete my branch on my side without side effect here ? I'm new to publishing on GitHub.

I wouldn't delete the branch on your fork, otherwise it will delete the code for the pull request. You should be able to delete the branch after it is merged.

**Comment by andresmanelli** [comment]
Hey I'm very sorry, I'll take a look this or next week !

Le mar. 13 juil. 2021 à 08:38, Fresher14 ***@***.***> a
écrit :

**Comment by nobodywasishere** [comment]
Nothing to apologize for! Open source work is thankless at times. I just wanted to make sure they didn't delete the branch before it had a chance to be merged, that's all.

**Comment by andresmanelli** [comment]
@Fresher14 Thank you for you PR !!

**Comment by andresmanelli** [comment]
@Fresher14 if you have a Twitter @ could you share it ? Thanks

**Pull request merged**
