### PR TITLE
This is modification request for bus 'data' and real numbers

### PR DESCRIPTION
**Pull request by Fresher14**
Mod1: a tab was lacking. This generated errors in 'data' for bus
Mod2: real numbers were not supported so far

### CODE REVIEW

**Comment by andresmanelli** [comment]
@Fresher14 , could you post here an example vcd/config file for the real numbers ? Thanks !

**Comment by Fresher14** [comment]
Here is a VCD. For config file, I added an auto mode. But I will try to create one.

```
$comment
TOOL:	simvision(64)	20.11-a001
$end

$date
    Apr 16, 2021 08:25:13
$end

$timescale
    0.01fs
$end


$scope module testbench $end

$scope module mytopmodule $end

$scope module mymodule $end
$var wire 1 ! ipg_clk $end
$var wire 1 " ips_byte_7_0 $end
$var wire 1 # ips_module_en $end
$var wire 16 $ ips_rdata [15:0] $end
$upscope $end

$upscope $end

$upscope $end

$var real 64 % discrete(gndsub) $end
$enddefinitions $end
#113166083000000
$dumpvars
1!
0"
0#
b0 $
r0.0045927214034875534 %
$end
#113167274000000
0!
#113168465000000
1!
#113169494622715
r0.0045927213892679713 %
#113169656000000
0!
#113170847000000
1!
#113172038000000
0!
#113173229000000
1!
#113174420000000
0!
#113175611000000
1!
#113176802000000
0!
#113177993000000
1!
#113179184000000
0!
#113180375000000
1!
#113181566000000
0!
#113182757000000
1!
#113183948000000
0!
#113185139000000
1!
#113186330000000
0!
#113187521000000
1!
#113188712000000
0!
#113189903000000
1!
#113191094000000
0!
#113192285000000
1!
#113193476000000
0!
#113194667000000
1!
#113195858000000
0!
#113197049000000
1!
#113198240000000
0!
#113199431000000
1!
#113200622000000
0!
#113201813000000
1!
#113203004000000
0!
#113204195000000
1!
#113205386000000
0!
#113206577000000
1!
#113207768000000
0!
#113208959000000
1!
#113210150000000
0!
#113211341000000
1!
#113212532000000
0!
#113213723000000
1!
#113214914000000
0!
#113216105000000
1!
#113217296000000
0!
#113218487000000
1!
#113219678000000
0!
#113220869000000
1!
#113222060000000
0!
#113223251000000
1!
#113224442000000
0!
#113225633000000
1!
#113226824000000
0!
#113228015000000
1!
#113229206000000
0!
#113230397000000
1!
b1000000000100 $
1"
1#
#113231588000000
0!
#113232779000000
1!
0#
#113233970000000
0!
#113235161000000
1!
b0 $
#113236352000000
0!

```

**Comment by Fresher14** [comment]
Here is generated wavedrom:

```
{
    "signal": [
        {
            "name": "testbench.mytopmodule.mymodule.ipg_clk",
            "wave": "10101010101010101010101010101010101010101010101010101010101",
            "data": []
        },
        {
            "name": "testbench.mytopmodule.mymodule.ips_byte_7_0",
            "wave": "0.....................................................1....",
            "data": []
        },
        {
            "name": "testbench.mytopmodule.mymodule.ips_module_en",
            "wave": "0.....................................................1.0..",
            "data": []
        },
        {
            "name": "testbench.mytopmodule.mymodule.ips_rdata[15:0]",
            "wave": "=.....................................................=...=",
            "data": [
                "0",
                "1004",
                "0"
            ]
        },
        {
            "name": ".discrete(gndsub)",
            "wave": "=..=.......................................................",
            "data": [
                "0.0045927214034875534",
                "0.0045927213892679713"
            ]
        }
    ],
    "config": {
        "hscale": 1
    }
}

```

**Comment by andresmanelli** [comment]
I'm wondering how did you handle the float in timescale (`0.01fs`), and what is your config auto mode.

Also, it would be nice to format the reals in scientific notation, something like 
```diff
diff --git a/vcd2wavedrom.py b/vcd2wavedrom.py
index 4a327df..b54534d 100644
--- a/vcd2wavedrom.py
+++ b/vcd2wavedrom.py
@@ -164,7 +164,7 @@ def dump_wavedrom(vcd_dict, timescale):
                                     format(int(j[1], 2), 'X')
                             )
                         else:
-                            drom['signal'][idromsig]['data'].append(j[1])
+                            drom['signal'][idromsig]['data'].append("{:.3e}".format(float(j[1])))
                     else:
                         digit = 'x'
             else:
```

**Comment by Fresher14** [comment]
'auto mode' is pre-processing to clean VCD (there was another issue with some bus) + modify all timings to finally have a timescale = 1

With formated real numbers:
image

**Comment by andresmanelli** [comment]
> 'auto mode' is pre-processing to clean VCD (there was another issue with some bus) + modify all timings to finally have a timescale = 1
> It is selected when no config file is provided.

Ah ok, that could be nice to have if you don't mind sharing it, on another issue/PR.

> With formated real numbers:
> image
> 
> Source:
> image

Cool, I'll merge this after the changes are committed

**Comment by Fresher14** [comment]
I'm currently checking robustness. I can push a new code in current PR ?

**Comment by andresmanelli** [comment]
I prefer to address one issue per PR if possible, if the original issue is fixed with the tab, and the real numbers are correctly shown, let's merge this and describe/fix the new features in another issue/PR.

**Comment by Fresher14** [comment]
I just pushed modification for float only: can you review ?

**Comment by andresmanelli** [comment]
Thanks for the contribution !

**Pull request merged**
